# Climate-Biomass Analysis Component Configuration
# Author: Diego Bengochea

# Data paths and directories
data:
  # Climate data processing
  climate_outputs: "climate_outputs"           # Raw climate GRIB/TIF files
  harmonized_dir: "harmonized_climate"         # Harmonized raster outputs
  bioclim_dir: "bioclimatic_variables"         # Bioclimatic variables (bio1-bio19)
  anomaly_dir: "climate_anomalies"             # Climate anomaly outputs
  
  # Biomass integration
  biomass_diff_dir: "interannual_biomass_differences_relative"  # Biomass difference maps
  temp_resampled_dir: "temp_resampled_biomass"  # Temporary resampled biomass files
  training_dataset: "ml_training_dataset.csv"   # Final ML training dataset
  clustered_dataset: "ml_dataset_with_clusters.csv"  # Dataset with spatial clusters
  
  # Reference data
  spain_boundary: "spain_boundary.shp"         # Spain boundary shapefile
  
# Time period definitions
time_periods:
  # Reference period for calculating climatology
  reference:
    start_year: 1981
    end_year: 2010
    rolling: true                             # Use Sep-Aug rolling years
    
  # Analysis period for anomaly calculation
  analysis:
    start_year: 2017
    end_year: 2024
    rolling: true                             # Use Sep-Aug rolling years

# Bioclimatic variables configuration
bioclim:
  # Variables to calculate (bio1-bio19)
  variables: ['bio1', 'bio2', 'bio3', 'bio4', 'bio5', 'bio6', 'bio7', 'bio8', 
              'bio9', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14', 'bio15', 
              'bio16', 'bio17', 'bio18', 'bio19']
  
  # Temperature unit conversion
  temp_conversion: 0.1                        # Convert from Kelvin*10 to Celsius
  
  # Precipitation scaling
  precip_scaling: 1000.0                      # Convert from m to mm

# Climate raster processing
climate_processing:
  # Target CRS for climate data
  target_crs: "EPSG:25830"                    # Spain national CRS
  
  # Resampling method for raster operations
  resampling_method: "bilinear"
  
  # Climate data file patterns
  temp_pattern: "2t_*.tif"                    # Temperature files
  precip_pattern: "tp_*.tif"                  # Precipitation files
  
  # Raster harmonization
  harmonization:
    chunk_size: 1000                          # Chunk size for large raster processing
    compress: "lzw"                           # Output compression

# Biomass integration parameters
biomass_integration:
  # Biomass file patterns
  pattern: "*_rel_change_*.tif"               # Biomass difference file pattern
  resampling_method: "bilinear"               # Resampling method for biomass data
  
  # Quality control
  max_valid_pixels: 1000000                   # Maximum pixels to process per dataset
  remove_outliers: true                       # Remove statistical outliers
  outlier_threshold: 3.0                      # Standard deviations for outlier detection

# Spatial analysis configuration
spatial_analysis:
  # Semivariogram calculation
  max_points_per_bin: 10000                   # Maximum point pairs per distance bin
  n_reference_points: 10000                   # Number of reference points to sample
  sample_fraction: 0.1                       # Fraction of pixels to sample for analysis
  
  # Distance binning
  max_distance_km: 500                        # Maximum distance for semivariogram (km)
  n_distance_bins: 50                         # Number of distance bins
  
  # Clustering parameters
  clustering:
    method: "kmeans"                          # Clustering algorithm
    n_clusters_range: [10, 50]               # Range of clusters to test
    min_cluster_size: 100                     # Minimum points per cluster
    
# Machine learning optimization
optimization:
  # Bayesian optimization settings
  n_trials: 1000                             # Number of optimization trials per run
  n_runs: 10                                 # Number of independent optimization runs
  random_seeds: [42, 123, 456, 789, 101112, 131415, 161718, 192021, 222324, 252627]
  
  # Cross-validation strategy
  cv_strategy:
    method: "spatial"                         # Spatial cross-validation
    test_blocks: 2                            # Number of spatial blocks for testing
    validation_blocks_range: [2, 4]          # Range of validation blocks
  
  # Feature selection
  features:
    # Bioclimatic variables to exclude from analysis
    exclude_bio_vars: ['bio8', 'bio9', 'bio18', 'bio19']  # Temperature and precipitation of wettest/driest quarters
    
    # Feature preprocessing
    standardize: true                         # Standardize features before ML
    remove_correlated: true                   # Remove highly correlated features
    correlation_threshold: 0.95               # Correlation threshold for removal
  
  # XGBoost hyperparameter ranges
  hyperparameters:
    n_estimators: [50, 500]                   # Number of trees
    max_depth: [3, 10]                        # Maximum tree depth
    learning_rate: [0.01, 0.3]               # Learning rate
    subsample: [0.6, 1.0]                     # Subsample ratio
    colsample_bytree: [0.6, 1.0]             # Feature subsample ratio
    min_child_weight: [1, 10]                # Minimum child weight
    reg_alpha: [0, 10]                        # L1 regularization
    reg_lambda: [1, 10]                       # L2 regularization
  
  # Early stopping
  early_stopping:
    patience: 40                              # Trials without improvement before stopping
    min_trials: 100                           # Minimum trials before early stopping

# Output configuration
output:
  # File formats
  raster_format: "GTiff"                      # Output raster format
  vector_format: "ESRI Shapefile"             # Output vector format
  
  # Compression and optimization
  compression: "lzw"                          # Raster compression method
  create_overviews: true                      # Create overview pyramids
  
  # Output organization
  create_subdirectories: true                 # Organize outputs in subdirectories
  preserve_intermediate: false                # Keep intermediate processing files
  
# Logging configuration
logging:
  level: "INFO"                               # Logging level (DEBUG, INFO, WARNING, ERROR)
  log_file: null                              # Log file path (null = console only)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Processing configuration
processing:
  # Multiprocessing
  n_workers: 4                                # Number of parallel workers
  chunk_size: 1000                            # Chunk size for parallel processing
  
  # Memory management
  max_memory_gb: 8                            # Maximum memory usage (GB)
  cleanup_intermediate: true                  # Clean up intermediate files
  
  # Progress reporting
  show_progress: true                         # Show progress bars
  progress_update_interval: 10                # Progress update interval (seconds)