# Climate-Biomass Analysis Component Configuration
# Author: Diego Bengochea

# Time period definitions
time_periods:
  # Reference period for calculating climatology
  reference:
    start_year: 1985
    end_year: 2015
    rolling: true                             # Use Sep-Aug rolling years
    
  # Analysis period for anomaly calculation
  analysis:
    # start_year: 2017
    # end_year: 2024
    # rolling: true  
    start_year: 2015
    end_year: 2024
    rolling: true                            # Use Sep-Aug rolling years

# Climate processing configuration  
climate_processing:
  # Variable patterns (restore original functionality)
  variable_patterns:
    temperature: "2t_*.tif"    # Temperature variable names
    precipitation: "tp_*.tif"    # Precipitation variable names
  
  # File pattern for processed climate files
  file_pattern: "{var}_{year}-{month}.tif"    # Pattern from your original script
  
  # Resampling method
  resampling_method: "bilinear"
  
  # Data organization
  temporal_ranges:
    historical: [1983, 2013]                  # First GRIB file range
    recent: [2014, 2024]                      # Second GRIB file range

# Bioclimatic variables configuration
bioclim:
  # Variables to calculate (bio1-bio19)
  variables: ['bio1', 'bio4', 'bio5', 'bio6', 'bio7', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14', 'bio15', 'bio16', 'bio17']
  
  # Temperature unit conversion
  temp_conversion: 0.1                        # Convert from Kelvin*10 to Celsius
  
  # Precipitation scaling
  precip_scaling: 1.0                         # No scaling for precipitation
  
  # Rolling year configuration
  rolling_months: [9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8]  # Sep-Aug

# Spatial analysis configuration
spatial:
  # Semivariogram calculation
  max_lag_distance: 300000                    # Maximum lag distance in meters
  n_lags: 50                                  # Number of lag bins
  
  max_points_per_bin: 1000
  n_reference_points: 100000
  n_distance_bins: 20

  # Autocorrelation analysis
  sill_threshold: 0.95                        # Threshold for 95% of sill
  knee_sensitivity: 1.0                       # Sensitivity for knee detection
  
  # Clustering configuration
  autocorr_factor: 1.5                        # Factor to multiply autocorr range
  elbow_sensitivity: 1.0                      # Sensitivity for elbow detection
  max_clusters: 15                            # Maximum number of clusters to test
  sample_fraction: 0.1

# Machine learning optimization configuration
optimization:
  # Optimization runs
  n_trials: 1000                             # Trials per optimization run
  n_runs: 10                                 # Independent optimization runs
  random_seeds: [42, 123, 456, 789, 999, 111, 222, 333, 444, 555]
  
  # Cross-validation strategy
  cv_strategy:
    method: "spatial"                         # Spatial cross-validation
    test_blocks: 2                            # Spatial blocks for testing
    validation_blocks_range: [3, 4]          # Range for validation blocks
    
  # Feature selection and processing
  features:
    exclude_bio_vars: ['bio8', 'bio9', 'bio18', 'bio19']  # Exclude problematic bio vars
    standardize: true                         # Standardize features
    correlation_threshold: 0.95               # Correlation threshold for feature removal
    
  # Model hyperparameters
  hyperparameters:
    n_estimators: [50, 300]                   # Range for number of estimators
    max_depth: [3, 8]                        # Range for maximum depth
    subsample: [0.6, 1.0]                     # Range for subsample ratio
    colsample_bytree: [0.6, 1.0]              # Range for feature sampling
    learning_rate: [0.01, 0.3]                # Range for learning rate
    reg_alpha: [0, 0.5]                        # Range for L1 regularization
    reg_lambda: [0, 0.5]                      # Range for L2 regularization
    min_child_weight: [1, 10]
    
  # Early stopping
  early_stopping:
    patience: 40                              # Trials without improvement
    min_trials: 100                           # Minimum trials before stopping
    
  # Feature selection constraints
  max_features: 10                            # Maximum number of features to select

# SHAP Analysis configuration
shap_analysis:
  
  # Model filtering parameters
  model_filtering:
    r2_threshold: 0.2                         # Minimum R² threshold for model inclusion
    r2_threshold_interactions: 0.2            # R² threshold for interaction analysis
    top_percentile_interactions: 10           # Top percentile of models for interactions
    min_selection_freq_interactions: 0.3      # Minimum selection frequency for interaction features
  
  # Analysis parameters
  analysis:
    # SHAP importance calculation
    shap_max_samples: 1000
    shap_max_background: 100
    
    # Permutation importance calculation
    perm_max_samples: 5000
    perm_n_repeats: 10
    
    # PDP analysis
    pdp_max_samples: 3000
    pdp_background_size: 1000
    pdp_n_top_features: 6
    pdp_x_range: [-2.5, 2.5]
    pdp_lowess_frac: 0.3
    pdp_n_models_subsample: 50
    
    # Interaction analysis
    interaction_max_samples: 1000
    interaction_max_background: 200
    interaction_n_top_features: 6
    interaction_feature_1: "bio12"            # Annual precipitation
    interaction_feature_2: "bio12_3yr"        # 3-year accumulated precipitation

# Variable name mapping for readable labels
variable_mapping:
  # Temperature variables
  bio1: "Annual temp."
  bio2: "Diurnal temp. range"
  bio3: "Isothermality"
  bio4: "Temp. seasonality"
  bio5: "Max temp. of warmest month"
  bio6: "Min temp. of coldest month"
  bio7: "Annual temp. range"
  bio8: "Temp. of wettest quarter"
  bio9: "Temp. of driest quarter"
  bio10: "Temp. of warmest quarter"
  bio11: "Temp. of coldest quarter"
  
  # Precipitation variables
  bio12: "Annual prec."
  bio13: "Prec. of wettest month"
  bio14: "Prec. of driest month"
  bio15: "Prec. seasonality"
  bio16: "Prec. of wettest quarter"
  bio17: "Prec. of driest quarter"
  bio18: "Prec. of warmest quarter"
  bio19: "Prec. of coldest quarter"
  
  # Other variables
  pdsi: "Palmer drought severity index"
  spei: "Stand. precip. evapotrans. index"
  vpd: "Vapor pressure deficit"
  pet: "Potential evapotranspiration"

# Processing configuration
processing:
  # Parallel processing
  n_workers: -1                               # Number of workers (-1 for all cores)
  chunk_size: 1000                            # Chunk size for processing
  
  # Memory management
  memory_limit: "8GB"                         # Memory limit per worker
  
  # Quality control
  validate_inputs: true                       # Validate input data
  check_spatial_alignment: true               # Check raster alignment
  
# Logging configuration
logging:
  level: "INFO"                               # Logging level
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
# File I/O configuration
io:
  # Raster settings
  compress: "lzw"                             # Compression for output rasters
  tiled: true                                 # Use tiled rasters
  blockxsize: 512                             # Block size X
  blockysize: 512                             # Block size Y
  
  # CSV settings
  csv_chunksize: 10000                        # Chunk size for CSV processing
  
# Geographic configuration
geographic:
  # Target coordinate reference system
  target_crs: "EPSG:25830"                    # ETRS89 / UTM zone 30N
  
  # Resampling method
  resampling_method: "bilinear"               # Default resampling method
  
  # No data value
  nodata: -9999                               # No data value for rasters
