# SHAP Analysis Configuration
# Separate configuration for comprehensive SHAP analysis pipeline

# Data paths
paths:
  # Input paths
  models_dir: "results/climate_biomass_analysis/models_remove_4"
  clustered_dataset: "results/climate_biomass_analysis/biomass_climate_data_with_clusters_20250509_100039.csv"
  
  # Output paths
  shap_analysis_dir: "results/shap_analysis"
  shap_figures_dir: "results/shap_analysis/figures"

# Model filtering parameters
model_filtering:
  r2_threshold: 0.2  # Minimum R² threshold for model inclusion
  r2_threshold_interactions: 0.2  # R² threshold for interaction analysis
  top_percentile_interactions: 10  # Top percentile of models for interactions
  min_selection_freq_interactions: 0.3  # Minimum selection frequency for interaction features

# Analysis parameters
analysis:
  # SHAP importance calculation
  shap_max_samples: 1000
  shap_max_background: 100
  
  # Permutation importance calculation
  perm_max_samples: 5000
  perm_n_repeats: 10
  
  # PDP analysis
  pdp_max_samples: 3000
  pdp_background_size: 1000
  pdp_n_top_features: 6
  pdp_x_range: [-2.5, 2.5]
  pdp_lowess_frac: 0.3
  pdp_n_models_subsample: 50
  
  # Interaction analysis
  interaction_max_samples: 1000
  interaction_max_background: 200
  interaction_n_top_features: 6

# Visualization parameters
visualization:
  # General plotting
  dpi: 300
  font_family: "Arial"
  font_size: 8
  
  # Figure-specific parameters
  top_n_features_barplots: 10
  r2_histogram_bins: 30
  
  # PDP visualization
  pdp_panel_ncols: 2
  pdp_lowess_frac_viz: 0.6
  
  # Main figure parameters
  main_fig_size: [7.5, 3.5]
  main_fig_width_ratios: [0.4, 0.6]
  
  # Interaction heatmap
  interaction_feature_1: "bio12"      # Annual precipitation
  interaction_feature_2: "bio12_3yr"  # 3-year accumulated precipitation
  interaction_n_bins: 60
  interaction_percentile_clip: 98

# Variable name mapping for readable labels
variable_mapping:
  # Temperature variables
  bio1: "Annual temp."
  bio2: "Diurnal temp. range"
  bio3: "Isothermality"
  bio4: "Temp. seasonality"
  bio5: "Max temp. of warmest month"
  bio6: "Min temp. of coldest month"
  bio7: "Annual temp. range"
  bio8: "Temp. of wettest quarter"
  bio9: "Temp. of driest quarter"
  bio10: "Temp. of warmest quarter"
  bio11: "Temp. of coldest quarter"
  
  # Precipitation variables
  bio12: "Annual prec."
  bio13: "Prec. of wettest month"
  bio14: "Prec. of driest month"
  bio15: "Prec. seasonality"
  bio16: "Prec. of wettest quarter"
  bio17: "Prec. of driest quarter"
  bio18: "Prec. of warmest quarter"
  bio19: "Prec. of coldest quarter"
  
  # Other variables
  pdsi: "Palmer drought severity index"
  spei: "Stand. precip. evapotrans. index"
  spi: "Standardized precipitation index"
  pet: "Potential evapotranspiration"
  aet: "Actual evapotranspiration"
  growing_season_length: "Growing season length"
  frost_days: "Number of frost days"
  heat_wave_days: "Heat wave days"
  dry_days_sequence: "Consecutive dry days"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
