# ALS PNOA Processing Configuration
# Author: Diego Bengochea

# Component metadata
component:
  name: "als_pnoa"
  version: "1.0.0"
  description: "PNOA LiDAR processing for training data preparation"

# Processing parameters
processing:
  # Target years for processing
  target_years: [2017, 2018, 2019, 2020, 2021]
  
  # Target coordinate reference system (EPSG code)
  target_crs: 'EPSG:25830'  # UTM Zone 30N
  
  # File pattern matching
  patterns:
    sentinel2_mosaic: 'sentinel2_mosaic_{year}_*.tif'
    pnoa_coverage: '*.shp'
    pnoa_data: 'NDSM-VEGETACION-*.tif'
  
  # Output file naming
  output_naming:
    # Pattern: PNOA_{year}_{ndsm_part}_epsg_{crs_code}.tif
    # Example: PNOA_2021_NDSM-VEGETACION-H30-0177-COB2_epsg_25830.tif
    template: 'PNOA_{year}_{ndsm_part}_epsg_{crs_code}.tif'
    crs_code_from_epsg: true  # Extract CRS code from EPSG (e.g., 25830 from EPSG:25830)

# Data validation settings
validation:
  # Required file patterns for validation
  required_patterns:
    sentinel2: 'sentinel2_mosaic_*.tif'
    pnoa_coverage: '*.shp'
    pnoa_data: 'NDSM-VEGETACION-*-COB2.tif'
  
  # Minimum expected files
  min_sentinel2_tiles: 1
  min_pnoa_coverage_files: 1
  min_pnoa_data_files: 1

# Output format settings
output:
  # Raster format parameters
  driver: 'GTiff'
  dtype: 'float32'
  compress: 'lzw'
  nodata: -9999
  
  # File organization
  create_year_subdirs: false  # Keep all files in single directory
  overwrite_existing: false   # Skip existing files by default

# UTM zone configuration
utm_zones:
  # Mapping of UTM zones to EPSG codes
  zone_29: 'EPSG:25829'
  zone_30: 'EPSG:25830'
  zone_31: 'EPSG:25831'
  
  # Primary UTM zone for output standardization
  primary_zone: 30

# Logging configuration
logging:
  level: "INFO"
  component_name: "als_pnoa"

# Performance settings
performance:
  # Memory management
  chunk_size: 1024  # Tile chunk size for processing
  max_workers: 4    # Maximum parallel workers (if implemented)
  
  # File I/O settings
  buffer_size: 1048576  # 1MB buffer for file operations

# Quality control
quality_control:
  # Check for spatial overlap between Sentinel-2 and PNOA tiles
  verify_intersection: true
  
  # Minimum intersection area (as fraction of tile)
  min_intersection_fraction: 0.1
  
  # Check file sizes
  min_file_size_mb: 0.1  # Minimum expected file size
  max_file_size_mb: 1000  # Maximum reasonable file size

# Data source information
data_sources:
  # PNOA (Plan Nacional de Ortofotografía Aérea)
  pnoa:
    provider: "Instituto Geográfico Nacional (IGN) - España"
    description: "PNOA LiDAR NDSM vegetation height data"
    url: "https://pnoa.ign.es/"
    license: "Open data - CC BY 4.0"
  
  # Sentinel-2
  sentinel2:
    provider: "European Space Agency (ESA)"
    description: "Sentinel-2 summer mosaic composites"
    processing: "Generated by sentinel2_processing component"

# File patterns documentation
file_patterns:
  input_examples:
    sentinel2: "sentinel2_mosaic_2021_T30SYJ.tif"
    pnoa_coverage: "COBERTURA_LiDAR_HU30_2021.shp"
    pnoa_data: "NDSM-VEGETACION-H30-0177-COB2.tif"
  
  output_examples:
    standardized: "PNOA_2021_NDSM-VEGETACION-H30-0177-COB2_epsg_25830.tif"