# Sentinel-2 Processing Configuration
# =============================================================================

# Processing Parameters
processing:
  n_scenes: 12                    # Number of best scenes to select for mosaic
  chunk_size: 2048                # Chunk size for dask processing
  cloud_threshold: 1              # Initial cloud cover threshold (%)
  years: [2019, 2021, 2022, 2023] # Years to process
  min_month: 6                    # Start month for summer period
  max_month: 9                    # End month for summer period
  tile_size: 12288                # Processing tile size (2048*6)
  
# Data Configuration  
data:
  bands: ['red', 'green', 'blue', 'nir', 'swir16', 'swir22', 'rededge1', 'rededge2', 'rededge3', 'nir08', 'scl']
  bands_drop: ['scl']             # Bands to drop after masking
  min_n_items: 40                 # Minimum number of scenes required
  max_cloud_threshold: 61         # Maximum cloud threshold to try
  stac_url: "https://earth-search.aws.element84.com/v1"
  
# Scene Classification Layer (SCL) valid classes
scl:
  valid_classes: [4, 5, 6, 11]    # vegetation, bare soil, water, snow and ice

# Paths - UPDATE THESE TO YOUR SPECIFIC PATHS
paths:
  spain_polygon: "/Users/diegobengochea/git/iberian.carbon/data/SpainPolygon/gadm41_ESP_0.shp"
  output_dir: "/Users/diegobengochea/git/iberian.carbon/data/S2_summer_mosaics/"
  downsampled_dir: "/Users/diegobengochea/git/iberian.carbon/data/S2_mosaics_downsampled/"
  merged_dir: "/Users/diegobengochea/git/iberian.carbon/data/S2_mosaics_merged/"
  
# Compute Resources
compute:
  n_workers: 8
  threads_per_worker: 3
  memory_per_worker: "20Gb"
  
# Post-processing Configuration
postprocessing:
  downsample:
    scale_factor: 10              # Downsampling scale factor
    resampling_method: "average"  # Resampling method for downsampling
    compression: "LZW"            # Output compression
  
  merge:
    compression: "LZW"            # Output compression for merged files
    
# Robustness Assessment
robustness:
  min_scenes: 5                   # Minimum scenes for robustness test
  max_scenes: 30                  # Maximum scenes for robustness test
  step: 5                         # Step size for scene number testing
  n_samples: 10                   # Number of random samples per n_scenes
  
# Consistency Analysis
consistency:
  sample_size: 10000              # Sample size for KS tests
