# Configuration for biomass allometry fitting pipeline
# Author: Diego Bengochea

# Data input configuration
data:
  # NFI training data (shapefiles with AGB, BGB, BGB_Ratio, ForestType, coordinates)
  nfi_data_dir: '/Users/diego/git/iberian.carbon/data/nfi/spain/processed/'
  nfi_shapefile_pattern: 'nfi4_{year}_biomass.shp'
  
  # Canopy height maps for sampling (country-wide rasters)
  height_maps_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_full_country_interpolated/'
  height_map_pattern: 'canopy_height_{year}_100m.tif'
  
  # Forest types hierarchy table
  forest_types_path: '/Users/diego/git/iberian.carbon/data/stocks_NFI4/Forest_Types_Tiers.csv'
  
  # Years to process (intersection of NFI and height map availability)
  target_years: [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Height-AGB allometry fitting parameters
height_agb:
  # Quantile regression settings
  quantiles: [0.15, 0.85]  # Lower and upper quantile bounds for confidence intervals
  alpha: 0.05              # Regularization parameter for quantile regression
  
  # Data filtering
  min_samples: 10          # Minimum samples required for fitting per forest type
  max_height: 50.0         # Maximum height threshold (meters)
  min_height: 1.0          # Minimum height threshold (meters)

# BGB-AGB ratio calculation parameters
bgb_agb:
  # Statistical calculation settings
  min_samples: 25          # Minimum samples for ratio calculation per forest type
  percentiles: [5, 50, 95] # Percentiles to calculate (p5, mean, p95)
  
  # Note: Uses existing BGB_Ratio column from NFI data (not recalculated)

# Outlier removal configuration
outlier_removal:
  enabled: true            # Whether to remove outliers before fitting
  contamination: 0.12      # Expected proportion of outliers (for Elliptic Envelope)

# Hierarchical forest type levels (processed in order)
hierarchy:
  levels:
    General:
      tier: 0
      description: "Overall general relationships using all forest types"
    
    Clade:
      tier: 1  
      description: "Broad taxonomic groupings (Coniferous, Broadleaved, etc.)"
      
    Family:
      tier: 2
      description: "Taxonomic families within clades"
      
    Genus:
      tier: 3
      description: "Taxonomic genera within families"
      
    ForestType:
      tier: 4
      description: "Specific forest types (MFE classifications)"

# Quality filters for fitted allometries
quality_filters:
  min_r2: 0.1              # Minimum R-squared value for height-AGB relationships
  min_slope: 0.0           # Minimum slope value (expect positive growth)

# Output configuration
output:
  # Height-AGB allometry results (compatible with existing biomass estimation pipeline)
  height_agb_path: '/Users/diego/git/iberian.carbon/data/stocks_NFI4/H_AGB_Allometries_Tiers_ModelCalibrated_Quantiles_15-85_OnlyPowerLaw.csv'
  
  # BGB ratio results (compatible with existing biomass estimation pipeline)  
  bgb_ratios_path: '/Users/diego/git/iberian.carbon/data/stocks_NFI4/BGBRatios_Tiers.csv'

# Logging configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(levelname)s - %(message)s'
