# Default configuration for Biomass Estimation Pipeline
# Author: Diego Bengochea

# Data paths and directories
data:
  # Input data directories
  input_data_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_full_country_interpolated/'
  masks_dir: '/Users/diego/git/iberian.carbon/data/forest_type_masks/100m/'
  
  # Reference data files
  allometries_dir: '/Users/diego/git/iberian.carbon/data/stocks_NFI4/H_AGB_Allometries_Tiers_ModelCalibrated_Quantiles_15-85_OnlyPowerLaw.csv'
  forest_type_dir: '/Users/diego/git/iberian.carbon/data/stocks_NFI4/Forest_Types_Tiers.csv'
  bgb_coeffs_dir: '/Users/diego/git/iberian.carbon/data/stocks_NFI4/BGBRatios_Tiers.csv'
  mfe_dir: '/Users/diego/git/iberian.carbon/data/MFESpain/'
  
  # Land cover masking
  corine_land_cover: '/Users/diego/git/iberian.carbon/data/corine_land_cover/U2018_CLC2018_V2020_20u1.tif'
  
  # Output directories
  output_base_dir: '/Users/diego/git/iberian.carbon/data'
  biomass_no_masking_dir: 'biomass_no_LC_masking'
  biomass_with_mask_dir: 'with_annual_crop_mask'
  
  # Output subdirectories for different biomass types
  agbd_dir: 'AGBD_MC_100m'
  bgbd_dir: 'BGBD_MC_100m'
  tbd_dir: 'TBD_MC_100m'

# Processing parameters
processing:
  # Height thresholds
  height_threshold: 0.0  # Minimum canopy height in meters for allometry application
  
  # Forest type processing
  compute_no_arbolado: true  # Whether to compute non-forest areas
  
  # File patterns and filtering
  file_pattern: '*.tif'
  target_years: ['2017', '2018', '2019', '2020']
  
  # Masking parameters
  annual_crop_values: [12, 13, 14]  # Corine land cover values for arable land

# Monte Carlo simulation parameters
monte_carlo:
  num_samples: 250  # Number of Monte Carlo samples per pixel
  seed: 42  # Random seed for reproducibility

# Output configuration
output:
  types: ['agbd', 'bgbd', 'total']  # Output map types to generate
  measures: ['mean', 'uncertainty']  # Statistical measures to output
  
  # File naming patterns
  output_prefix: 'S2'  # Prefix for output files
  
  # GeoTIFF optimization settings
  geotiff:
    tiled: true
    blockxsize: 256
    blockysize: 256
    compress: 'LZW'
    dtype: 'float32'

# Distributed computing parameters
compute:
  num_workers: 4  # Number of Dask workers
  memory_limit: '41GB'  # Memory limit per worker
  threads_per_worker: 1  # Threads per worker
  chunk_size: 1500  # Chunk size for Dask arrays (pixels)

# Forest type hierarchy configuration
forest_types:
  tier_names:
    0: 'Dummy'
    1: 'Clade'
    2: 'Family'
    3: 'Genus'
    4: 'ForestTypeMFE'
  
  # Caching
  cache_file: 'forest_type_cache.csv'
  use_cache: true

# Logging configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(levelname)s - %(message)s'

# Masking and merging configuration
masking:
  # Annual cropland masking
  target_extensions: ['.tif', '.tiff', '.img']
  recursive_processing: true
  skip_existing: true
  
  # Script-specific paths for mask_annual_cropland.py
  target_input_dir: '/Users/diego/git/iberian.carbon/data/biomass_no_LC_masking'
  masked_output_dir: 'with_annual_crop_mask'
  
  # Merging configuration
  merge_years: ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
  merged_output_dir: 'biomass_maps_merged_with_annual_crop_mask'
  
  # Base directory for merging script
  merge_base_dir: '/Users/diego/git/iberian.carbon/data/with_annual_crop_mask/'
  
  # Biomass type patterns for merging
  biomass_patterns: ['AGBD*', 'BGBD*', 'TBD*']
