# Default configuration for Canopy Height Deep Learning Pipeline


# Data parameters
data:
  data_dir: '/Users/diegobengochea/git/iberian.carbon/data/S2_PNOA_DATASET/'
  checkpoint_dir: '/Users/diegobengochea/git/iberian.carbon/deep_learning/canopy_height_checkpoints_loss_L1log_batch_balanced_alpha=0.6/'
  checkpoint_path: null  # Optional path to resume from checkpoint
  
  # Data module parameters
  patch_size: 256
  batch_size: 32
  length: null  # Optional length override
  num_workers: 0
  seed: 43554578
  
  # Data handling
  nan_target: -1.0
  nan_input: 0.0
  
  # Dataset split parameters
  split_ratios: [0.8, 0.1, 0.1]  # train, val, test
  grid_size: 8  # For random grid cell assignment

# Augmentation parameters
augmentation:
  # Geometric augmentation probabilities
  horizontal_flip_p: 0.5
  vertical_flip_p: 0.5
  rotation_p: 0.5
  rotation_degrees: 90
  
  # Image intensity augmentation probabilities and parameters
  gaussian_noise_p: 0.3
  gaussian_noise_std: 0.01
  brightness_p: 0.3
  brightness_factor: 0.01
  contrast_p: 0.3
  contrast_factor: 0.01
  
  # Mask augmentation parameters
  mask_noise_p: 0.2
  mask_noise_std: 0.01
  
  # Height filtering parameters
  max_height_threshold: 60.0

# Balanced sampling parameters
sampling:
  # Diversity thresholds for patch selection
  max_diversity_threshold: 8.0
  min_diversity_threshold: 4.0
  
  # Patch quality constraints
  max_attempts: 1200
  initial_max_nodata_ratio: 0.4
  initial_max_low_veg_ratio: 0.4
  
  # Data values
  nan_value: -32767.0
  
# Training parameters (references model config for lr)
training:
  max_epochs: 100
  predict_patch_size: 4096
  learning_rate: 1e-4  # Base learning rate (max_lr defined in scheduler section)
  patience: 15
  early_stopping_patience: 50
  val_check_interval: 1
  log_steps: 50
  load_weights_only: false
  accumulate_grad_batches: 1
  num_sanity_val_steps: 1

# Model parameters
model:
  model_type: 'unet'
  backbone: 'efficientnet-b4'
  in_channels: 10
  num_outputs: 1
  target_range: 'universal'
  
  # Data handling
  nan_value_target: -1.0
  nan_value_input: 0.0
  
  # Height range definitions for metrics calculation
  metric_ranges:
    universal: [[0, 2], [2, 6], [6, 10], [10, 15], [15, 20], [20, 25], [25, 30]]
  
  # Height range definitions for range metrics (HeightRangeMetrics class)
  height_ranges: [[0, 1], [1, 2], [2, 4], [4, 8], [8, 12], [12, 16], [16, 20], [20, 25], [25, .inf]]

# Loss function parameters (centralized from canopy_height_regression.py)
loss:
  percentile_range: [7.5, 92.5]
  lambda_reg: 0.0
  alpha: 0.6
  max_height: 30.0
  eps: 1e-6
  weights: true

# Optimizer and scheduler parameters (centralized from canopy_height_regression.py)
optimizer:
  type: 'AdamW'
  weight_decay: 0.01
  
scheduler:
  type: 'OneCycleLR'
  max_lr: 2e-4
  pct_start: 0.2
  div_factor: 15
  final_div_factor: 100
  three_phase: false
  anneal_strategy: 'cos'

# Model configurations for testing
test_models:
  - path: "/Users/diegobengochea/git/iberian.carbon/deep_learning/canopy_height_checkpoints_3ensemble/last0-2m.ckpt"
    name: "deeplabv3plus_efficientb4_0-2m"
  - path: "/Users/diegobengochea/git/iberian.carbon/deep_learning/canopy_height_checkpoints_3ensemble/last2-10m.ckpt"
    name: "deeplabv3plus_efficientb4_2-10m"
  - path: "/Users/diegobengochea/git/iberian.carbon/deep_learning/canopy_height_checkpoints_3ensemble/last10m+.ckpt"
    name: "deeplabv3plus_efficientb4_10m+"

# Compute settings
compute:
  accelerator: 'auto'  # Will be determined at runtime (mps/cpu)
  devices: 'auto'

# Prediction settings
prediction:
  output_dir: 'canopy_height_predictions'
  checkpoint_path: '/path/to/your/checkpoint.ckpt'  # Replace with actual path
  patch_size: 6144
  stride: 256  # Overlap between predictions
  
  # Geographic filtering
  spain_shapefile: '/Users/diegobengochea/git/iberian.carbon/data/SpainPolygon/gadm41_ESP_0.shp'
  
  # Raster output settings
  raster:
    dtype: 'float32'
    crs: 'epsg:25830'
    nodata: -1.0
    compress: 'lzw'
    tiled: true
    blockxsize: 256
    blockysize: 256

# Evaluation settings
evaluation:
  output_dir: "/Users/diegobengochea/git/iberian.carbon/deep_learning/evaluation_results/"
  checkpoint_path: "/Users/diegobengochea/git/iberian.carbon/deep_learning/canopy_height_checkpoints_loss_L1log_balanced_alpha_0.5/last.ckpt"
  
  # Plot settings
  plot:
    bin_width: 5.0
    max_height: 40.0
    figure_dpi: 300
    bbox_inches: 'tight'

# Post-processing pipeline settings
post_processing:
  # Step 1: Merge predictions into tiles
  merge:
    input_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/0/'
    output_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_120km/'
    spain_shapefile: '/Users/diego/git/iberian.carbon/data/SpainPolygon/gadm41_ESP_0.shp'
    tile_size_km: 120  # Tile size in kilometers (120x120km)
    buffer_meters: 2560  # Buffer to prevent stitching artifacts
    target_crs: 'EPSG:25830'  # UTM30 for Spain
    resolution_meters: 10  # Original resolution
    nodata_value: -9999.9999
    compression: 'lzw'
    num_workers: 22  # Number of parallel workers
    
    # Year timestamp mapping
    year_timestamps:
      1483225200: 2017
      1514761200: 2018
      1546297200: 2019
      1577833200: 2020
      1609455600: 2021
      1640991600: 2022
      1672527600: 2023
      1704063600: 2024
  
  # Step 2: Sanitize predictions (outlier removal and interpolation)
  sanitize:
    input_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_120km/'
    processed_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_120km_nan_flagged/'
    interpolated_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_120km_interpolated/'
    interpolation_masks_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_120km_interpolation_mask/'
    summary_file: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/sanitization_summary.csv'
    
    # Outlier detection parameters
    upper_threshold: 60.0  # Maximum realistic vegetation height (meters)
    lower_threshold: 0.0   # Minimum realistic vegetation height (meters)
    
    # Processing parameters
    num_workers: 12  # Number of parallel workers
    
  # Step 3: Downsample and create final country-wide mosaics
  final_merge:
    input_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_120km_interpolated/'
    output_dir: '/Users/diego/git/iberian.carbon/data/canopy_height_predictions/merged_full_country_interpolated/'
    file_pattern: 'canopy_height_*_*.tif'
    target_resolution: 100  # Final resolution in meters
    compression: 'lzw'
    resampling_method: 'average'  # Resampling method for downsampling

# Logging settings
logging:
  level: 'INFO'
  log_dir: 'logs'
