# Biomass Analysis Component Configuration
# Centralized settings for all analysis scripts

component: "biomass_analysis"
version: "1.0.0"

# Output settings
output:
  save_monte_carlo_samples: true
  save_intermediate_results: true

# Analysis parameters
analysis:
  target_years: [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
  pixel_area_ha: 1  # Each 100m x 100m pixel = 1 ha
  
# Monte Carlo simulation settings
monte_carlo:
  num_samples: 1000
  spatial_block_size: 800  # pixels (80km at 100m resolution)
  confidence_interval:
    low_percentile: 2.5   # For 95% confidence interval
    high_percentile: 97.5
  parallel_processing:
    enabled: false  # Set to true to enable parallel processing
    num_workers: 4
  random_seed: 42

# File naming patterns
file_patterns:
  biomass_mean: '{biomass_type}_S2_mean_{year}_100m_{suffix}_merged.tif'
  biomass_uncertainty: '{biomass_type}_S2_uncertainty_{year}_100m_{suffix}_merged.tif'
  biomass_types: ['TBD', 'AGBD', 'BGBD']

# Height range settings
height_ranges:
  bins: [0, 2, 6, 10, 20]  # Creates ranges: 0-2m, 2-6m, 6-10m, 10-20m, 20m+
  labels: ['0_2m', '2_6m', '6_10m', '10_20m', '20m_plus']
  # Height file naming pattern
  height_file_pattern: 'canopy_height_{year}_100m.tif'  # in canopy_height_dir

# Landcover settings (for Corine Land Cover analysis)
landcover:
  groups:
    urban: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]                  # 1-11
    agricultural: [15, 16, 17, 18, 19, 20, 21, 22]                # 15-22  
    natural: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]  # 23-39

# Quality control
quality_control:
  max_biomass_threshold: 1500  # Filter unrealistically high values
  min_biomass_threshold: 0     # Minimum biomass threshold

# Interannual analysis settings
interannual:
  # For raster difference maps
  differences:
    create_10km_resampled: false  # Whether to create 10km resampled versions
  
  # For transition analysis
  transitions:
    save_transition_data: true   # Whether to save raw pixel-level transition data
    pixel_area_ha: 1             # Area per pixel in hectares
    max_biomass_threshold: 1500   # Maximum biomass threshold for quality control
  
  # For carbon flux calculations  
  carbon_fluxes:
    biomass_to_carbon: 0.5        # Factor to convert biomass to carbon
    n_combinations: 10000         # Number of random combinations for flux calculations
    create_diagnostics: true      # Whether to create diagnostic plots

# Logging
logging:
  level: 'INFO'
